name: Deploy to S3 using Docker
description: Uses Python in a Docker container to deploy to AWS.
inputs:
  bucket:
    description: Name of the S3 bucket to upload the files to.
    required: true
  bucket-region:
    description: The region of the S3 bucket.
    required: false
    default: us-east-1
  dist-files:
    description: The folder containing the deployable files.
    required: false
    default: dist
outputs:
  website-url:
    description: The URL of the deployed website.
runs:
  using: Docker
  image: Dockerfile