name: Build & Push local Dockerfile.
description: This composite action simply builds the specified Dockerfile and pushes it to the DockerHub account with the provided credentials.
inputs:
  file:
    description: Path to reach the Dockerfile.
    required: false
    default: Dockerfile
  tags:
    description: Name of the user/image-name. For instance knphilip/image:latest.
    required: true
  username:
    description: Username of the DockerHub account to push to.
    required: true
  password:
    description: Password of the DockerHub account to push to.
    required: true
runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ${{ inputs.file }}
        tags: ${{ inputs.tags }}