# Uses an official lightweight Alpine image as a base.
FROM alpine:latest

# Note that this could also be used with your
# programming language of choice.

# Run Hello World from a Docker container!
CMD ["echo", "Hello World!"]